<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="out\**" />
    <EmbeddedResource Remove="out\**" />
    <None Remove="out\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\R.NET\RDotNet.csproj" />
  </ItemGroup>

</Project>
